name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: build
      run: make build-client
    - name: build
      run: make build-server
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        path: |
          client.out 
          server.out
